name: web_static_screen_size
description: static mediaQuery size for web
version: 1.0.0
repository: https://github.com/mutasimbalila/web_static_screen_size.git

topics:
  - Size
  - MediaQuery
  - Web
  - Responsive

license: MIT License
environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
